language: minimal
os: linux
before_install:
- sudo apt-get update -qq
install:
- sudo apt-get install -qq pandoc texlive-latex-base texlive-latex-recommended lmodern texlive-fonts-recommended
before_script: cd dev
script:
- mkdir -p ./{pdf,html}
- make
- tar -czvf specs.tar.gz html pdf
deploy:
  provider: releases
  name: ${TRAVIS_COMMIT}
  skip_cleanup: true
  file_glob: true
  file:
    - html/*
    - pdf/*
    - specs.tar.gz
  api_key:
    secure: i1ZTLLYcFTXz3XGDZa8Tj3vgQ+NpQ+IJeRrIyMq88hr9Xj/xoaLrdzscBQKZxwyLSC8MOgu3UT2OxUg1RQs3LHSt1yWlroHoisv5yUIwngiwLPpf4pQkVqBrirS+Ogu2NASstSAAIfkBPJqDZdZqHAryxqzlQCjApk44aEso1Ij/kD0cGUW4TMuW9GI0AfoYpFrdguBwcbBml9kcgIGSupsQgVQ+cnVzR5Ek6tJGVQ9j80fZhF6a3ZZ+zFtTzQek7uEuzp3kzMEfQMM7hEQpRDNZdlLwkBusKjNRtPkkMyAmf1Dl/9Oiyqej4u6Y0gNBIv5Z8D1b6PWUm/wSGSrS+VQJV3V4OJ3TyzSlJE+yot1CawNbEa66zmhdWDObNar7gPr54IcebjEnSZj+rYmUikme+nd7uGCEz9Q1ouTJ0xn3iFzwDPcg06OS74qs67xNBR16AUOWfDyripCWtBoUXMerqtFaVkY4oJJF7Db8HtQPD1+kN8L0q/rPexqmAxGYtYTUKrOigypVoLhfiWJCTk7L/ghraDGhgRXfb2wAMl2t3K8BtmhY4uVPpq7En3IOdOcvEaSLKUjy84jP5DvewplVTXHUh5RS5xyVr1zPaYZB1rEGLVhhdLOV67SZICXUuMjyp3pTIGn0Ig6Zo2u7uROAaCntIGhi+I2J/cRJXes=
  on:
    repo: algorandfoundation/specs
    branch: master
