language: minimal
os: linux
dist: focal
before_install:
- sudo apt-get update -qq
install:
- sudo apt-get install -qq pandoc texlive-latex-base texlive-latex-recommended lmodern texlive-fonts-recommended
before_script: cd dev
script:
- mkdir -p ./{pdf,html}
- make
- tar -czvf specs.tar.gz html pdf
deploy:
  provider: releases
  name: ${TRAVIS_COMMIT}
  skip_cleanup: true
  file_glob: true
  file:
    - html/*
    - pdf/*
    - specs.tar.gz
  api_key:
    secure: "BdUwVRQNMANfbtfB4oGTdClUTS435xhm7cdb9P4WvfbRwuCvEEN3kxwftlrkzO9eVkimm5U1m1RyPkQI3m4zHi99Rr3yv5M8dOUasltt9hGHWx+mdDiIo7mlLHYFZP2L+cyC9HrCWnGm6K8q53N8OtzGX1ZsUaXYFJSjAdVoL25rGJD+ng/Zyleb3ZMB4B52Uzo+RyyJeYwYRGoxVEvbSm2jQ8Lx/J2s7AnG0a4z7MFHAzvAgwTBmLsIwD/rKuC/F5wLCi2+4H696z/sUu6AsMW431tYJpoPRzE2WG793u5frzZL7a5CExNxuiLtfVQUyIdnB20Ve/15Py0Y3FNUUf+jq2G6xfDjR3WU4LBqHAmQrzNWBRFl79v1bozajBnS6JwePISkpovZJXUj3mt9fgy7vT4tl4jksOX0B4BuWk90mWJfZJsdZbgQXQA9hG/TKnhS+wrNMTfSOMh7od+ZXko9TdKQoyed2SOSrzgJWcP7Lxf1z4hFOcy9X9UgkkCfBc0gc5Xwt0SHi40siFx2JtdpqwPylmBVMnmpdvCV9s/VZrcXrmgqXeRLCr4yRc37plSs+yagi7q++DdCy9U+JDTqRmzY5f5R9kF13u1O+NmYkbJgAmXbX84yWqOQF6LuJWeZKJXAyAF02Jw/qI7AZEcIXpxQ3uZc9aqb6/ED8xU="
  on:
    repo: algorandfoundation/specs
    branch: master
