language: minimal
os: linux
dist: focal
before_install:
- sudo apt-get update -qq
install:
- sudo apt-get install -qq pandoc texlive-latex-base texlive-latex-recommended lmodern texlive-fonts-recommended texlive-latex-extra
before_script: cd dev
script:
- mkdir -p ./{pdf,html}
- make
- tar -czvf specs.tar.gz html pdf
deploy:
  provider: releases
  name: ${TRAVIS_COMMIT}
  skip_cleanup: true
  file_glob: true
  file:
    - html/*
    - pdf/*
    - specs.tar.gz
  api_key:
    secure: "JfHbCmz+xNZp6L5UWp6uxNThg3zj4TxWO5x4KK6StZb1KMKlYtci6BJTYY6yAJtS3pZmUJrTK7nbpu7lzMvL99q8wBVIcflEG+XFnvaeJfH0lNY8LVAwdrxM5DlY/w083ivFNrMznFOZEnyruqFrczaodJ5M9MSnly49+hxE20CMnjmbOMg/PjB+GCXO+XT1f7wByclmeXwmPqLR6RMS8xzO35cX42fE8qOayEduRM27BDfLy3uSsx06deq0u7m/8Xj6IVja6/0F4NEVM9nr8c9FQobqXaxfGOch5TFUYUg/BqsPLVVonATUsbVcocJbgYbxbQdkXGnF1XxF/EcMcaqZwt2qCH1EZ3r+Tsil4f8oyQl+/xm/BesbCUH+AGPNqR3Y9cQgm0JHk3K9tE4FDLtBzS6u8m/szqHm/N0Abgca7MkJiddmuPRjeKiAqZED7g4HDYL608YmzAyBVNIftOFw/VezHlWLrl9P/r+VxtvZeM85dr5xODsiL9CHv9T1V/wg4AvRNaM0Ld6eFYduR9v1W1ZyQvyotps/0ahN6ZbOjK6fZSpnXVgX3oDo81EHMQqL8M4fERvmoApdGJOLkUGwY/AhRVD0FJaUwh7EoJnsWoP9brjw6NYvqhdWTBu8Xc1+eKRimEA+BCogx3qpSF1jg9XSCLkT9F3Yq/6ihUU="
  on:
    repo: algorandfoundation/specs
    branch: master
