language: minimal
os: linux
dist: focal
before_install:
- sudo apt-get update -qq
install:
- sudo apt-get install -qq pandoc texlive-latex-base texlive-latex-recommended lmodern texlive-fonts-recommended texlive-latex-extra
before_script: cd dev
script:
- mkdir -p ./{pdf,html}
- make
- tar -czvf specs.tar.gz html pdf
deploy:
  provider: releases
  name: ${TRAVIS_COMMIT}
  skip_cleanup: true
  file_glob: true
  file:
    - html/*
    - pdf/*
    - specs.tar.gz
  api_key:
    secure: "I4fRtF1hHRUxvFA/gEsTkdmJR9pJhQVNSL+akfrJ9hAPs0VGA+l2mOoaFKadQMbxuKH2AQBxfBJvyVvWZipr58D0GwmozI+zKpR9Jaz35hHhT3/G1A9EdCgQycT8xSymvyEK50l+yV04nAO/Xr9aqCmkbGY+ksczue8SGxCH5jIxlNZr3OPnr4nVe+TdPjMkIYRXBb1JHTYwKoPuzWPeUiJGP6Wpf4MSaW3CaMB9XK6HNeF/2YzwxiHya2x68Yivy45wVRdLPRgnI9Ilm5W4cEaWnx4cn63tUieqOMpY3B8hmAQZfol7AeSCygjL9s2BjPaLI010BzY+u13LW5PXk95ziSDG827dMt/H6n3HLExOs0tK9CU2wauBE9w31UQW6YSSer2+T3cAJ7Nzj8GbEBazz0yokQU01hc6g0YEbFfhGExc8siknCMBa26rtBNIpZf7nkiXIqkNrGljuVrj/a/Rs0bvnS70mtiSxC/2oH1HEvQm4wdv7Zk/j16pMrWkuYZBKc+2mGEg6vDOIcvH2Vcq96S4itzIjs2wW20dijeVaUyBTpICGFKFIqfuOLdUjSDH5fO1KFhR1PEBb+eN4/la+h6KJC7xQhqgzMLk1iVktNPCLr0dBtgyjpJVmJ51+Pcc3XdSucO4wCSgPrdeAr3t07WCb8MC8lbbFoS5KTU="
  on:
    repo: algorandfoundation/specs
    branch: master
